services:
  - type: web
    name: movie-server
    env: python
    plan: free
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      playwright install chromium
    startCommand: gunicorn server:app --workers=2 --threads=4 --worker-class=gthread --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
